version: '3.8'

services:

  web:
    image: ghcr.io/dmitriy282/my-app:${IMAGE_TAG:-latest}
    ports:
      - "5000:5000"
    restart: unless-stopped

    environment:
      - DATABASE_URL=postgresql://space_admin:supersecret@db:5432/space_logbook
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=space_admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=space_logbook
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U space_admin" ]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

  alloy:
    image: grafana/alloy:v1.2.1
    container_name: alloy
    volumes:
      - ./config.alloy:/etc/alloy/config.alloy:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    command:
      - run
      - --server.http.listen-addr=0.0.0.0:12345
      - /etc/alloy/config.alloy
    environment:
      - GC_LOKI_URL=https://insight-logs-prod-eu-north-0.grafana.net/loki/api/v1/push
      - GC_LOKI_USER=grafanacloud-livelypumpkin1825-alert-state-history
      - GC_PROMETHEUS_URL=https://prometheus-prod-39-prod-eu-north-0.grafana.net/api/prom/push
      - GC_PROMETHEUS_USER=grafanacloud-livelypumpkin1825-prom
      - GC_API_KEY=${GRAFANA_API_KEY}
    restart: unless-stopped

volumes:
  pgdata:
