version: '3.8'

services:
  my-app:
    image: ghcr.io/dmitriy282/my-app:latest
    container_name: my-app-container
    ports:
      - "5000:5000"
    restart: unless-stopped
    
  web:
    build: ./app
    ports:
      - "5001:5000"
    environment:
      - DATABASE_URL=postgresql://space_admin:supersecret@db:5432/space_logbook
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started

  db:
    image: postgres:15-alpine
    environment:
      - POSTGRES_USER=space_admin
      - POSTGRES_PASSWORD=supersecret
      - POSTGRES_DB=space_logbook
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U space_admin"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"

volumes:
  pgdata:
