name: Build Docker Image Only

on:
  push:
    branches:
      - '*'
env:
  # Задаем единое имя образа для всех шагов
  # Важно: GHCR требует, чтобы имя владельца было в нижнем регистре
  IMAGE_NAME: ghcr.io/dmitriy282/my-app:latest
  
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
          contents: read
          packages: write
    # Додаємо блок services для запуску контейнерів поруч із тестами

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
          
      - name: Install dependencies and run tests
        env:
          # Жестко переопределяем URL, чтобы избежать подключения к Postgres 'db'
          DATABASE_URL: 'sqlite:///:memory:'
        run: |
          cd ./app
          pip install -r requirements.txt
          pytest test_app.py -v
      - uses: actions/checkout@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./app
          push: true
          tags: ${{ env.IMAGE_NAME }}
      
      - name: Deploy to Server via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            ssh ubuntu@18.153.90.238 -p 22
            # Логинимся в GHCR уже внутри вашего сервера
            echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            
            # Скачиваем обновленный образ
            docker pull ghcr.io/${{ github.repository_owner }}/my-app:latest
            
            # Останавливаем и удаляем старый контейнер (если он запущен)
            docker stop my-app-container || true
            docker rm my-app-container || true
            
            # Запускаем новый контейнер
            docker run -d --name my-app-container -p 80:80 ghcr.io/${{ github.repository_owner }}/my-app:latest
    
