name: Build Docker Image Only

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest

    # Додаємо блок services для запуску контейнерів поруч із тестами
    
services:

      db:

        image: postgres:15-alpine # Використовуємо легку версію Postgres

        env:

          POSTGRES_USER: test_user

          POSTGRES_PASSWORD: test_password

          POSTGRES_DB: test_db

        # Прокидаємо порт, щоб додаток міг підключитися через localhost

        ports:

          - 5432:5432

        # Перевірка здоров'я, щоб тести не почалися до того, як БД буде готова

        options: >-

          --health-cmd pg_isready

          --health-interval 10s

          --health-timeout 5s

          --health-retries 5
          
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Install dependencies and Run Tests

        env:

          # Тепер вказуємо реальне підключення до піднятого Postgres

          DATABASE_URL: postgresql://postgres:postgres@db:5432/space_logbook

          TESTING: "True"
          
      - name: Build Docker image
        uses: docker/build-push-action@v5.3.0
        with:
          context: ./app
          push: false
          tags: test-image:latest
          
   
        run: |
          cd ./app
          pip install -r requirements.txt
          pytest test_app.py -v
